-- ENTRY outage hardening: runtime load-shedding gate for nonessential work.
-- Migration filename generated by Supabase CLI.
--
-- IMPORTANT: this migration intentionally leaves all targeted high-frequency
-- cron jobs disabled. It only makes their future execution pass through a
-- NORMAL / DEGRADED / SEVERE gate.

create table if not exists public.entry_background_runtime_control (
  control_key text primary key,
  mode text not null,
  reason text,
  updated_at timestamptz not null default now(),
  constraint entry_background_runtime_control_singleton
    check (control_key = 'global'),
  constraint entry_background_runtime_control_mode
    check (mode in ('NORMAL', 'DEGRADED', 'SEVERE'))
);

alter table public.entry_background_runtime_control enable row level security;

revoke all on table public.entry_background_runtime_control from public;
revoke all on table public.entry_background_runtime_control from anon;
revoke all on table public.entry_background_runtime_control from authenticated;

insert into public.entry_background_runtime_control (
  control_key,
  mode,
  reason,
  updated_at
)
values (
  'global',
  'SEVERE',
  'Initialized by ENTRY outage hardening; high-frequency jobs remain disabled until staged recovery is approved.',
  now()
)
on conflict (control_key) do nothing;

create or replace function public.run_entry_background_job_v1(
  p_job_name text
)
returns jsonb
language plpgsql
security definer
set search_path = 'public', 'pg_temp'
as $function$
declare
  v_job_name text := btrim(coalesce(p_job_name, ''));
  v_mode text;
  v_allowed boolean := false;
begin
  if v_job_name not in (
    'cleanup-edge-rate-limits',
    'community-message-push-stale-sweeper',
    'community-message-push-worker',
    'entry-mobile-push-receipts',
    'entry-observability-incident-reconcile',
    'entry-plate-ocr-queue',
    'entry-web-push-dispatch',
    'expire-stale-records'
  ) then
    raise exception 'Unsupported ENTRY background job: %', v_job_name
      using errcode = '22023';
  end if;

  select c.mode
    into v_mode
  from public.entry_background_runtime_control c
  where c.control_key = 'global';

  v_mode := coalesce(v_mode, 'SEVERE');

  if v_mode = 'NORMAL' then
    v_allowed := true;
  elsif v_mode = 'DEGRADED' then
    -- During partial provider/database degradation, only the two bounded
    -- mobile communication workers are allowed to probe. Expensive OCR,
    -- web-push fan-out, observability reconciliation, and cleanup defer.
    v_allowed := v_job_name in (
      'community-message-push-worker',
      'entry-mobile-push-receipts'
    );
  else
    v_allowed := false;
  end if;

  if not v_allowed then
    return jsonb_build_object(
      'ok', true,
      'ran', false,
      'job', v_job_name,
      'mode', v_mode,
      'reason', 'runtime_gate'
    );
  end if;

  case v_job_name
    when 'cleanup-edge-rate-limits' then
      perform public.cleanup_edge_rate_limit_buckets();

    when 'community-message-push-stale-sweeper' then
      perform public.sweep_stale_community_message_pushes();

    when 'community-message-push-worker' then
      perform public.trigger_community_message_push_worker();

    when 'entry-mobile-push-receipts' then
      perform public.trigger_entry_mobile_push_receipt_worker();

    when 'entry-observability-incident-reconcile' then
      perform public.reconcile_entry_observability_incidents_v1();
      perform public.reconcile_entry_observability_data_integrity_v1();

    when 'entry-plate-ocr-queue' then
      perform public.process_plate_ocr_queue();

    when 'entry-web-push-dispatch' then
      perform public.invoke_entry_web_push_dispatch_v1();

    when 'expire-stale-records' then
      perform public.expire_stale_records();
  end case;

  return jsonb_build_object(
    'ok', true,
    'ran', true,
    'job', v_job_name,
    'mode', v_mode
  );
end;
$function$;

revoke all on function public.run_entry_background_job_v1(text) from public;
revoke all on function public.run_entry_background_job_v1(text) from anon;
revoke all on function public.run_entry_background_job_v1(text) from authenticated;
grant execute on function public.run_entry_background_job_v1(text) to service_role;

-- Route the eight incident-relevant jobs through the runtime gate, but preserve
-- active=false. Reactivation remains an explicit, separate operational action.
do $do$
declare
  v_job record;
begin
  for v_job in
    select j.jobid, j.jobname
    from cron.job j
    where j.jobname in (
      'cleanup-edge-rate-limits',
      'community-message-push-stale-sweeper',
      'community-message-push-worker',
      'entry-mobile-push-receipts',
      'entry-observability-incident-reconcile',
      'entry-plate-ocr-queue',
      'entry-web-push-dispatch',
      'expire-stale-records'
    )
  loop
    perform cron.alter_job(
      v_job.jobid,
      command => format(
        'select public.run_entry_background_job_v1(%L);',
        v_job.jobname
      ),
      active => false
    );
  end loop;
end;
$do$;
