-- ENTRY outage hardening: make primary manual check-in idempotent.
-- Migration filename generated by Supabase CLI.
--
-- The mobile client already sends one stable client_reference per manual-entry
-- flow. Production stored the value but did not enforce uniqueness or replay
-- the original result after a commit-then-timeout retry.

create unique index if not exists uq_manual_entries_community_client_reference
  on public.manual_entries (community_id, client_reference)
  where client_reference is not null
    and btrim(client_reference) <> '';

CREATE OR REPLACE FUNCTION public.check_in_manual_entry(p_community_id uuid, p_manual_entry_name text, p_manual_entry_company text DEFAULT NULL::text, p_manual_entry_reason text DEFAULT NULL::text, p_is_pedestrian boolean DEFAULT false, p_photo_path text DEFAULT NULL::text, p_vehicle_photo_path text DEFAULT NULL::text, p_client_reference text DEFAULT NULL::text, p_destination_id uuid DEFAULT NULL::uuid, p_destination_label text DEFAULT NULL::text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
declare
  v_user_id uuid;
  v_now timestamptz := now();
  v_manual_entry_id uuid;
  v_entry_log_id uuid;
  v_name text;
  v_company text;
  v_reason text;
  v_is_pedestrian boolean;
  v_photo_path text;
  v_vehicle_photo_path text;
  v_destination_id uuid;
  v_destination_label text;
  v_destination_active boolean;
  v_linked_house_id uuid;
  v_linked_house_active boolean;
  v_metadata jsonb;
  v_client_reference text;
  v_existing_manual_entry public.manual_entries%rowtype;
  v_existing_entry_log_id uuid;
begin
  v_user_id := auth.uid();
  v_client_reference := nullif(trim(coalesce(p_client_reference, '')), '');
  v_name := nullif(trim(coalesce(p_manual_entry_name, '')), '');
  v_company := nullif(trim(coalesce(p_manual_entry_company, '')), '');
  v_reason := nullif(trim(coalesce(p_manual_entry_reason, '')), '');
  v_is_pedestrian := coalesce(p_is_pedestrian, false);
  v_photo_path := nullif(trim(coalesce(p_photo_path, '')), '');
  v_vehicle_photo_path := case
    when v_is_pedestrian then null
    else nullif(trim(coalesce(p_vehicle_photo_path, '')), '')
  end;
  v_destination_label := nullif(trim(coalesce(p_destination_label, '')), '');

  if v_user_id is null then
    raise exception 'Not authenticated'
      using errcode = '28000';
  end if;

  if p_community_id is null then
    raise exception 'community_id is required'
      using errcode = '22023';
  end if;

  if v_reason is null then
    raise exception 'manual_entry_reason is required'
      using errcode = '22023';
  end if;

  if v_destination_label is null then
    raise exception 'destination_label is required'
      using errcode = '22023';
  end if;

  if v_photo_path is null then
    raise exception 'photo_path is required for manual entry'
      using errcode = '22023';
  end if;

  if not v_is_pedestrian and v_vehicle_photo_path is null then
    raise exception 'vehicle_photo_path is required for manual vehicle entry'
      using errcode = '22023';
  end if;

  if not exists (
    select 1
    from public.communities c
    where c.id = p_community_id
      and c.is_active = true
  ) then
    raise exception 'Community is inactive or unavailable'
      using errcode = '42501';
  end if;

  if not exists (
    select 1
    from public.community_members cm
    where cm.user_id = v_user_id
      and cm.community_id = p_community_id
      and cm.is_active = true
      and cm.role in ('GUARD', 'ADMIN')
  ) then
    raise exception 'Not authorized to register manual entries in this community'
      using errcode = '42501';
  end if;

  -- Serialize one logical manual-entry operation only after current
  -- authentication, community status, and guard membership are verified.
  -- A replay never grants access; it only returns the result of an operation
  -- that already committed for the same guard and payload.
  if v_client_reference is not null then
    perform pg_advisory_xact_lock(
      hashtextextended(
        'check_in_manual_entry:' || p_community_id::text || ':' || v_client_reference,
        0
      )
    );

    select *
      into v_existing_manual_entry
    from public.manual_entries me
    where me.community_id = p_community_id
      and me.client_reference = v_client_reference
    limit 1;

    if found then
      if v_existing_manual_entry.guard_id <> v_user_id then
        raise exception 'client_reference is already owned by another guard'
          using errcode = '23505';
      end if;

      if v_existing_manual_entry.manual_entry_name is distinct from v_name
         or v_existing_manual_entry.manual_entry_company is distinct from v_company
         or v_existing_manual_entry.manual_entry_reason is distinct from v_reason
         or coalesce(v_existing_manual_entry.is_pedestrian, false) <> v_is_pedestrian
         or v_existing_manual_entry.destination_id is distinct from p_destination_id
         or (
           p_destination_id is null
           and btrim(coalesce(v_existing_manual_entry.destination_label, ''))
                <> coalesce(v_destination_label, '')
         ) then
        raise exception 'client_reference payload does not match the original manual entry'
          using errcode = '23505';
      end if;

      select el.id
        into v_existing_entry_log_id
      from public.entry_logs el
      where el.manual_entry_id = v_existing_manual_entry.id
        and el.action = 'CHECK_IN'
      order by el.action_at asc, el.created_at asc
      limit 1;

      if v_existing_entry_log_id is null then
        raise exception 'Existing manual entry is missing its CHECK_IN audit log'
          using errcode = 'P0001';
      end if;

      return jsonb_build_object(
        'ok', true,
        'duplicate', true,
        'manual_entry_id', v_existing_manual_entry.id,
        'entry_log_id', v_existing_entry_log_id,
        'community_id', v_existing_manual_entry.community_id,
        'action', 'CHECK_IN',
        'action_at', v_existing_manual_entry.checked_in_at,
        'access_source', 'MANUAL',
        'pass_type', 'MANUAL_ENTRY',
        'pass_type_label', 'Ingreso manual',
        'visitor_name', coalesce(
          v_existing_manual_entry.manual_entry_name,
          v_existing_manual_entry.destination_label,
          'Ingreso manual'
        ),
        'house_label', coalesce(v_existing_manual_entry.destination_label, 'General'),
        'destination_id', v_existing_manual_entry.destination_id,
        'destination_label', coalesce(v_existing_manual_entry.destination_label, 'General'),
        'method', 'MANUAL',
        'metadata', v_existing_manual_entry.metadata
      );
    end if;
  end if;

  if p_destination_id is not null then
    select
      cd.id,
      cd.name,
      cd.is_active,
      cd.linked_house_id,
      case
        when cd.linked_house_id is null then true
        else coalesce(h.is_active, false)
      end
      into
        v_destination_id,
        v_destination_label,
        v_destination_active,
        v_linked_house_id,
        v_linked_house_active
    from public.community_destinations cd
    left join public.houses h
      on h.id = cd.linked_house_id
     and h.community_id = cd.community_id
    where cd.id = p_destination_id
      and cd.community_id = p_community_id;

    if not found then
      raise exception 'Destination is missing or belongs to another community'
        using errcode = '42501';
    end if;

    if not v_destination_active then
      raise exception 'Destination is disabled'
        using errcode = '42501';
    end if;

    if v_linked_house_id is not null and not coalesce(v_linked_house_active, false) then
      raise exception 'Destination is blocked because its linked unit is suspended'
        using errcode = '42501';
    end if;
  end if;

  v_metadata := jsonb_build_object(
    'access_source', 'MANUAL',
    'pass_type', 'MANUAL_ENTRY',
    'pass_type_label', 'Ingreso manual',
    'house_label', coalesce(v_destination_label, 'General'),
    'destination_id', v_destination_id,
    'destination_label', coalesce(v_destination_label, 'General'),
    'method', 'MANUAL',
    'manual_entry_name', v_name,
    'manual_entry_company', v_company,
    'manual_entry_reason', v_reason,
    'is_pedestrian', v_is_pedestrian,
    'photo_path', v_photo_path,
    'vehicle_photo_path', v_vehicle_photo_path,
    'client_reference', v_client_reference
  );

  insert into public.manual_entries (
    community_id,
    guard_id,
    client_reference,
    manual_entry_name,
    manual_entry_company,
    manual_entry_reason,
    destination_id,
    destination_label,
    is_pedestrian,
    photo_path,
    vehicle_photo_path,
    status,
    checked_in_at,
    metadata
  )
  values (
    p_community_id,
    v_user_id,
    v_client_reference,
    v_name,
    v_company,
    v_reason,
    v_destination_id,
    coalesce(v_destination_label, 'General'),
    v_is_pedestrian,
    v_photo_path,
    v_vehicle_photo_path,
    'CHECKED_IN',
    v_now,
    v_metadata
  )
  returning id into v_manual_entry_id;

  insert into public.entry_logs (
    community_id,
    guard_id,
    action,
    action_at,
    method,
    photo_path,
    vehicle_photo_path,
    skip_photo_validation,
    exception_reason,
    manual_entry_id,
    metadata
  )
  values (
    p_community_id,
    v_user_id,
    'CHECK_IN',
    v_now,
    'MANUAL',
    v_photo_path,
    v_vehicle_photo_path,
    v_is_pedestrian,
    case when v_is_pedestrian then 'PEATON' else null end,
    v_manual_entry_id,
    v_metadata
  )
  returning id into v_entry_log_id;

  return jsonb_build_object(
    'ok', true,
    'manual_entry_id', v_manual_entry_id,
    'entry_log_id', v_entry_log_id,
    'community_id', p_community_id,
    'action', 'CHECK_IN',
    'action_at', v_now,
    'access_source', 'MANUAL',
    'pass_type', 'MANUAL_ENTRY',
    'pass_type_label', 'Ingreso manual',
    'visitor_name', coalesce(v_name, v_destination_label, 'Ingreso manual'),
    'house_label', coalesce(v_destination_label, 'General'),
    'destination_id', v_destination_id,
    'destination_label', coalesce(v_destination_label, 'General'),
    'method', 'MANUAL',
    'metadata', v_metadata
  );
end;
$function$

