-- ENTRY outage hardening: runtime load-shedding gate for nonessential work.
-- Migration filename generated by Supabase CLI.
--
-- IMPORTANT: this migration intentionally leaves all targeted high-frequency
-- cron jobs disabled. It only makes their future execution pass through a
-- NORMAL / DEGRADED / SEVERE gate.

create table if not exists public.entry_background_runtime_control (
  control_key text primary key,
  mode text not null,
  reason text,
  updated_at timestamptz not null default now(),
  constraint entry_background_runtime_control_singleton
    check (control_key = 'global'),
  constraint entry_background_runtime_control_mode
    check (mode in ('NORMAL', 'DEGRADED', 'SEVERE'))
);

alter table public.entry_background_runtime_control enable row level security;

revoke all on table public.entry_background_runtime_control from public;
revoke all on table public.entry_background_runtime_control from anon;
revoke all on table public.entry_background_runtime_control from authenticated;

insert into public.entry_background_runtime_control (
  control_key,
  mode,
  reason,
  updated_at
)
values (
  'global',
  'SEVERE',
  'Initialized by ENTRY outage hardening; high-frequency jobs remain disabled until staged recovery is approved.',
  now()
)
on conflict (control_key) do nothing;

-- Bound database-side dispatch before the runtime gate can ever permit work.
-- These limits are intentionally duplicated in the Edge Functions so an older
-- worker deployment cannot turn one cron tick into an unbounded recovery burst.

CREATE OR REPLACE FUNCTION public.trigger_community_message_push_worker()
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
declare
  v_secret text;
begin
  select ds.decrypted_secret into v_secret
  from vault.decrypted_secrets ds
  where ds.name='entry_community_message_worker_secret'
  order by ds.created_at desc
  limit 1;

  if nullif(v_secret,'') is null then
    raise exception 'ENTRY community message worker credential is not configured'
      using errcode='55000';
  end if;

  perform net.http_post(
    url => 'https://ytzvislhvrcdtkbtpbmu.supabase.co/functions/v1/smart-service',
    headers => jsonb_build_object(
      'Content-Type','application/json',
      'Authorization','Bearer ' || v_secret
    ),
    body => jsonb_build_object('limit',5),
    timeout_milliseconds => 9000
  );
end;
$function$;

CREATE OR REPLACE FUNCTION public.trigger_entry_mobile_push_receipt_worker()
 RETURNS bigint
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
declare
  v_secret text;
  v_request_id bigint;
begin
  select ds.decrypted_secret into v_secret
  from vault.decrypted_secrets ds
  where ds.name='entry_community_message_worker_secret'
  order by ds.created_at desc
  limit 1;

  if nullif(v_secret,'') is null then
    raise exception 'ENTRY mobile push receipt worker credential is not configured'
      using errcode='55000';
  end if;

  select net.http_post(
    url => 'https://ytzvislhvrcdtkbtpbmu.supabase.co/functions/v1/entry-push-receipts',
    headers => jsonb_build_object(
      'Content-Type','application/json',
      'Authorization','Bearer ' || v_secret
    ),
    body => jsonb_build_object('limit',50),
    timeout_milliseconds => 9000
  ) into v_request_id;

  return v_request_id;
end;
$function$;

CREATE OR REPLACE FUNCTION public.process_plate_ocr_queue()
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
declare
  v_item record;
  v_service_role_key text;
  v_dispatched integer := 0;
  v_failed_dispatch integer := 0;
begin
  select ds.decrypted_secret
  into v_service_role_key
  from vault.decrypted_secrets ds
  where ds.name = 'SUPABASE_SERVICE_ROLE_KEY'
  limit 1;

  if nullif(v_service_role_key, '') is null then
    return jsonb_build_object('dispatched',0,'dispatch_failed',0,'status','internal_auth_unavailable');
  end if;

  update public.plate_ocr_queue q
  set status='DONE', completed_at=coalesce(q.completed_at, now()), last_error=null
  from public.entry_logs el
  where el.id=q.entry_log_id
    and el.vehicle_plate_text is not null
    and q.status in ('PENDING','PROCESSING');

  for v_item in
    select q.id, q.entry_log_id, q.image_path, q.attempts, q.max_attempts
    from public.plate_ocr_queue q
    join public.entry_logs el on el.id = q.entry_log_id
    where q.status='PENDING'
      and q.scheduled_at <= now()
      and q.attempts < q.max_attempts
      and el.vehicle_plate_text is null
    order by q.created_at
    limit 3
    for update of q skip locked
  loop
    begin
      update public.plate_ocr_queue
      set status='PROCESSING', attempts=attempts+1, last_error=null
      where id=v_item.id;

      perform net.http_post(
        url := 'https://ytzvislhvrcdtkbtpbmu.supabase.co/functions/v1/extract-plate-text',
        headers := jsonb_build_object(
          'Content-Type','application/json',
          'Authorization','Bearer ' || v_service_role_key,
          'apikey',v_service_role_key
        ),
        body := jsonb_build_object(
          'image_path',v_item.image_path,
          'bucket','entry-photos',
          'entry_log_id',v_item.entry_log_id::text
        ),
        timeout_milliseconds := 15000
      );

      update public.plate_ocr_queue
      set status='PENDING', scheduled_at=now()+interval '2 minutes'
      where id=v_item.id and status='PROCESSING';

      v_dispatched := v_dispatched + 1;
    exception when others then
      update public.plate_ocr_queue
      set status=case when attempts>=max_attempts then 'FAILED' else 'PENDING' end,
          scheduled_at=case when attempts>=max_attempts then scheduled_at else now()+interval '2 minutes' end,
          last_error='OCR_DISPATCH_FAILED'
      where id=v_item.id;
      v_failed_dispatch := v_failed_dispatch + 1;
    end;
  end loop;

  update public.plate_ocr_queue
  set status='FAILED', last_error=coalesce(last_error,'OCR_MAX_ATTEMPTS_REACHED')
  where status='PENDING' and attempts>=max_attempts;

  return jsonb_build_object('dispatched',v_dispatched,'dispatch_failed',v_failed_dispatch,'status','ok');
end;
$function$;

create or replace function public.run_entry_background_job_v1(
  p_job_name text
)
returns jsonb
language plpgsql
security definer
set search_path = 'public', 'pg_temp'
as $function$
declare
  v_job_name text := btrim(coalesce(p_job_name, ''));
  v_mode text;
  v_allowed boolean := false;
begin
  if v_job_name not in (
    'cleanup-edge-rate-limits',
    'community-message-push-stale-sweeper',
    'community-message-push-worker',
    'entry-mobile-push-receipts',
    'entry-observability-incident-reconcile',
    'entry-plate-ocr-queue',
    'entry-web-push-dispatch',
    'expire-stale-records'
  ) then
    raise exception 'Unsupported ENTRY background job: %', v_job_name
      using errcode = '22023';
  end if;

  select c.mode
    into v_mode
  from public.entry_background_runtime_control c
  where c.control_key = 'global';

  v_mode := coalesce(v_mode, 'SEVERE');

  if v_mode = 'NORMAL' then
    v_allowed := true;
  elsif v_mode = 'DEGRADED' then
    -- During partial provider/database degradation, only the two bounded
    -- mobile communication workers are allowed to probe. Expensive OCR,
    -- web-push fan-out, observability reconciliation, and cleanup defer.
    v_allowed := v_job_name in (
      'community-message-push-worker',
      'entry-mobile-push-receipts'
    );
  else
    v_allowed := false;
  end if;

  if not v_allowed then
    return jsonb_build_object(
      'ok', true,
      'ran', false,
      'job', v_job_name,
      'mode', v_mode,
      'reason', 'runtime_gate'
    );
  end if;

  case v_job_name
    when 'cleanup-edge-rate-limits' then
      perform public.cleanup_edge_rate_limit_buckets();

    when 'community-message-push-stale-sweeper' then
      perform public.sweep_stale_community_message_pushes();

    when 'community-message-push-worker' then
      perform public.trigger_community_message_push_worker();

    when 'entry-mobile-push-receipts' then
      perform public.trigger_entry_mobile_push_receipt_worker();

    when 'entry-observability-incident-reconcile' then
      perform public.reconcile_entry_observability_incidents_v1();
      perform public.reconcile_entry_observability_data_integrity_v1();

    when 'entry-plate-ocr-queue' then
      perform public.process_plate_ocr_queue();

    when 'entry-web-push-dispatch' then
      perform public.invoke_entry_web_push_dispatch_v1();

    when 'expire-stale-records' then
      perform public.expire_stale_records();
  end case;

  return jsonb_build_object(
    'ok', true,
    'ran', true,
    'job', v_job_name,
    'mode', v_mode
  );
end;
$function$;

revoke all on function public.run_entry_background_job_v1(text) from public;
revoke all on function public.run_entry_background_job_v1(text) from anon;
revoke all on function public.run_entry_background_job_v1(text) from authenticated;
grant execute on function public.run_entry_background_job_v1(text) to service_role;

-- Route the eight incident-relevant jobs through the runtime gate, but preserve
-- active=false. Reactivation remains an explicit, separate operational action.
do $do$
declare
  v_job record;
begin
  for v_job in
    select j.jobid, j.jobname
    from cron.job j
    where j.jobname in (
      'cleanup-edge-rate-limits',
      'community-message-push-stale-sweeper',
      'community-message-push-worker',
      'entry-mobile-push-receipts',
      'entry-observability-incident-reconcile',
      'entry-plate-ocr-queue',
      'entry-web-push-dispatch',
      'expire-stale-records'
    )
  loop
    perform cron.alter_job(
      v_job.jobid,
      command => format(
        'select public.run_entry_background_job_v1(%L);',
        v_job.jobname
      ),
      active => false
    );
  end loop;
end;
$do$;
