
create table if not exists public.entry_performance_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  community_id uuid null references public.communities(id) on delete set null,
  actor_id uuid null references auth.users(id) on delete set null,
  source_surface text not null,
  metric_name text not null,
  duration_ms integer not null,
  status text not null default 'success',
  error_code text null,
  platform text null,
  app_version text null,
  route text null,
  metadata jsonb not null default '{}'::jsonb,
  constraint entry_performance_events_duration_ck check (duration_ms between 0 and 600000),
  constraint entry_performance_events_status_ck check (status in ('success','failed')),
  constraint entry_performance_events_surface_ck check (char_length(source_surface) between 1 and 64),
  constraint entry_performance_events_metric_ck check (char_length(metric_name) between 1 and 96)
);

create index if not exists idx_entry_performance_events_created_at
  on public.entry_performance_events (created_at desc);
create index if not exists idx_entry_performance_events_metric_created
  on public.entry_performance_events (metric_name, created_at desc);
create index if not exists idx_entry_performance_events_community_created
  on public.entry_performance_events (community_id, created_at desc);

alter table public.entry_performance_events enable row level security;
revoke all on table public.entry_performance_events from public, anon, authenticated;
grant select, insert, update, delete on table public.entry_performance_events to service_role;

create table if not exists public.entry_observability_incidents (
  id uuid primary key default gen_random_uuid(),
  fingerprint text not null,
  scope_key text not null,
  community_id uuid null references public.communities(id) on delete set null,
  capability text not null,
  event_type text not null,
  error_code text null,
  severity text not null,
  status text not null default 'open',
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  resolved_at timestamptz null,
  occurrence_count bigint not null default 1,
  last_details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint entry_observability_incidents_severity_ck
    check (severity in ('INFO','WARNING','ERROR','CRITICAL')),
  constraint entry_observability_incidents_status_ck
    check (status in ('open','resolved'))
);

create unique index if not exists ux_entry_observability_incidents_open
  on public.entry_observability_incidents (fingerprint, scope_key)
  where status = 'open';
create index if not exists idx_entry_observability_incidents_recent
  on public.entry_observability_incidents (last_seen_at desc);
create index if not exists idx_entry_observability_incidents_community
  on public.entry_observability_incidents (community_id, status, last_seen_at desc);

alter table public.entry_observability_incidents enable row level security;
revoke all on table public.entry_observability_incidents from public, anon, authenticated;
grant select, insert, update, delete on table public.entry_observability_incidents to service_role;

create or replace function public._entry_observability_actor_community_v1()
returns uuid
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select cm.community_id
  from public.community_members cm
  where cm.user_id = auth.uid()
    and cm.is_active = true
  order by case cm.role::text
    when 'ADMIN' then 1
    when 'GUARD' then 2
    when 'RESIDENT' then 3
    else 4
  end, cm.created_at desc
  limit 1
$$;

revoke all on function public._entry_observability_actor_community_v1() from public, anon, authenticated;
grant execute on function public._entry_observability_actor_community_v1() to service_role;

create or replace function public.record_entry_performance_v1(
  p_metric_name text,
  p_duration_ms integer,
  p_source_surface text default 'entry_web',
  p_status text default 'success',
  p_error_code text default null,
  p_platform text default null,
  p_app_version text default null,
  p_route text default null,
  p_community_id uuid default null
)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_actor uuid := auth.uid();
  v_role text := coalesce(current_setting('request.jwt.claim.role', true), '');
  v_community uuid;
  v_id bigint;
  v_metric text := left(regexp_replace(coalesce(p_metric_name,''), '[^a-zA-Z0-9_.:-]+', '_', 'g'), 96);
  v_surface text := left(regexp_replace(coalesce(p_source_surface,'entry_web'), '[^a-zA-Z0-9_.:-]+', '_', 'g'), 64);
  v_route text := nullif(left(regexp_replace(coalesce(p_route,''), '[0-9a-fA-F]{8}-[0-9a-fA-F-]{27,}', ':id', 'g'), 160), '');
  v_error text := nullif(left(regexp_replace(coalesce(p_error_code,''), '[^a-zA-Z0-9_.:-]+', '_', 'g'), 96), '');
begin
  if v_actor is null and v_role <> 'service_role' then
    raise exception 'Authentication required' using errcode='42501';
  end if;

  if p_duration_ms is null or p_duration_ms < 0 or p_duration_ms > 600000 then
    raise exception 'Invalid duration' using errcode='22023';
  end if;

  if nullif(v_metric,'') is null then
    raise exception 'Metric name required' using errcode='22023';
  end if;

  if coalesce(p_status,'success') not in ('success','failed') then
    raise exception 'Invalid performance status' using errcode='22023';
  end if;

  if v_role = 'service_role' then
    v_community := p_community_id;
  else
    v_community := public._entry_observability_actor_community_v1();
    if p_community_id is not null and p_community_id = v_community then
      v_community := p_community_id;
    end if;
  end if;

  insert into public.entry_performance_events (
    community_id, actor_id, source_surface, metric_name, duration_ms, status,
    error_code, platform, app_version, route, metadata
  )
  values (
    v_community, v_actor, v_surface, v_metric, p_duration_ms, coalesce(p_status,'success'),
    v_error, nullif(left(coalesce(p_platform,''),32),''),
    nullif(left(coalesce(p_app_version,''),48),''),
    v_route, '{}'::jsonb
  )
  returning id into v_id;

  return v_id;
end;
$$;

revoke all on function public.record_entry_performance_v1(text,integer,text,text,text,text,text,text,uuid)
  from public, anon;
grant execute on function public.record_entry_performance_v1(text,integer,text,text,text,text,text,text,uuid)
  to authenticated, service_role;

create or replace function public.record_entry_client_error_v1(
  p_error_code text,
  p_source_surface text default 'entry_web',
  p_platform text default null,
  p_app_version text default null,
  p_route text default null
)
returns uuid
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_actor uuid := auth.uid();
  v_role text := coalesce(current_setting('request.jwt.claim.role', true), '');
  v_community uuid;
  v_id uuid;
  v_error text := left(regexp_replace(coalesce(nullif(p_error_code,''),'CLIENT_UNHANDLED_ERROR'), '[^a-zA-Z0-9_.:-]+', '_', 'g'), 96);
  v_surface text := left(regexp_replace(coalesce(p_source_surface,'entry_web'), '[^a-zA-Z0-9_.:-]+', '_', 'g'), 64);
  v_route text := nullif(left(regexp_replace(coalesce(p_route,''), '[0-9a-fA-F]{8}-[0-9a-fA-F-]{27,}', ':id', 'g'),160),'');
begin
  if v_actor is null and v_role <> 'service_role' then
    raise exception 'Authentication required' using errcode='42501';
  end if;

  v_community := case when v_role='service_role' then null else public._entry_observability_actor_community_v1() end;

  insert into public.system_event_log (
    severity, module, event_type, message, details, community_id,
    user_id, actor_id, source, correlation_id
  )
  values (
    'ERROR',
    'client_runtime',
    'CLIENT_UNHANDLED_ERROR',
    'ENTRY client reported an unhandled runtime error',
    jsonb_strip_nulls(jsonb_build_object(
      'status','failed',
      'error_code',v_error,
      'error_fingerprint','client:' || lower(v_surface) || ':' || lower(v_error),
      'surface',v_surface,
      'platform',nullif(left(coalesce(p_platform,''),32),''),
      'app_version',nullif(left(coalesce(p_app_version,''),48),''),
      'route',v_route
    )),
    v_community, v_actor, v_actor, v_surface, null
  )
  returning id into v_id;

  return v_id;
end;
$$;

revoke all on function public.record_entry_client_error_v1(text,text,text,text,text) from public, anon;
grant execute on function public.record_entry_client_error_v1(text,text,text,text,text)
  to authenticated, service_role;

create or replace function public.record_entry_admin_operation_v1(
  p_operation text,
  p_status text,
  p_duration_ms integer default null,
  p_error_code text default null
)
returns uuid
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_actor uuid := auth.uid();
  v_community uuid;
  v_id uuid;
  v_operation text := left(regexp_replace(coalesce(p_operation,''), '[^a-zA-Z0-9_.:-]+', '_', 'g'), 96);
  v_status text := case when lower(coalesce(p_status,''))='success' then 'success' else 'failed' end;
  v_error text := nullif(left(regexp_replace(coalesce(p_error_code,''), '[^a-zA-Z0-9_.:-]+', '_', 'g'),96),'');
begin
  if v_actor is null then
    raise exception 'Authentication required' using errcode='42501';
  end if;

  select cm.community_id into v_community
  from public.community_members cm
  where cm.user_id=v_actor
    and cm.is_active=true
    and cm.role::text in ('ADMIN','GUARD')
  order by case cm.role::text when 'ADMIN' then 1 else 2 end, cm.created_at desc
  limit 1;

  if v_community is null then
    raise exception 'Admin or guard membership required' using errcode='42501';
  end if;

  insert into public.system_event_log (
    severity,module,event_type,message,details,community_id,user_id,actor_id,source
  )
  values (
    case when v_status='success' then 'INFO' else 'ERROR' end,
    'administration',
    case when v_status='success' then 'ADMIN_OPERATION_SUCCEEDED' else 'ADMIN_OPERATION_FAILED' end,
    case when v_status='success' then 'ENTRY administration operation succeeded' else 'ENTRY administration operation failed' end,
    jsonb_strip_nulls(jsonb_build_object(
      'status',v_status,
      'operation',v_operation,
      'duration_ms',case when p_duration_ms between 0 and 600000 then p_duration_ms else null end,
      'error_code',v_error,
      'error_fingerprint',case when v_status='failed' then 'administration:' || lower(v_operation) || ':' || lower(coalesce(v_error,'failed')) else null end
    )),
    v_community,v_actor,v_actor,'entry_web'
  )
  returning id into v_id;

  return v_id;
end;
$$;

revoke all on function public.record_entry_admin_operation_v1(text,text,integer,text) from public, anon;
grant execute on function public.record_entry_admin_operation_v1(text,text,integer,text)
  to authenticated, service_role;

create or replace function public.get_dashboard_stats()
returns table(
  accesses_today bigint,
  active_users bigint,
  units bigint,
  active_passes bigint
)
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare
  v_user uuid := auth.uid();
  v_community uuid;
  v_tz text := 'America/Tegucigalpa';
  v_start timestamptz;
  v_end timestamptz;
begin
  select cm.community_id into v_community
  from public.community_members cm
  where cm.user_id=v_user
    and cm.is_active=true
    and cm.role::text in ('ADMIN','GUARD')
  order by case cm.role::text when 'ADMIN' then 1 else 2 end
  limit 1;

  if v_community is null then
    raise exception 'ADMIN or GUARD role required' using errcode='42501';
  end if;

  select coalesce(nullif(cs.timezone,''),'America/Tegucigalpa')
  into v_tz
  from public.community_settings cs
  where cs.community_id=v_community;

  v_tz := coalesce(v_tz,'America/Tegucigalpa');
  v_start := date_trunc('day', now() at time zone v_tz) at time zone v_tz;
  v_end := v_start + interval '1 day';

  return query
  select
    (select count(*) from public.entry_logs el
      where el.community_id=v_community and el.action_at>=v_start and el.action_at<v_end),
    (select count(*) from public.community_members cm
      where cm.community_id=v_community and cm.is_active=true),
    (select count(*) from public.houses h
      where h.community_id=v_community),
    (select count(*) from public.visit_passes vp
      where vp.community_id=v_community and vp.status::text in ('ACTIVE','CHECKED_IN'));
end;
$$;

revoke all on function public.get_dashboard_stats() from public, anon;
grant execute on function public.get_dashboard_stats() to authenticated, service_role;

create or replace function public.admin_list_access_history_v2(
  p_community_id uuid,
  p_limit integer default 20,
  p_offset integer default 0,
  p_search text default null,
  p_type text default null,
  p_method text default null,
  p_evidence text default null,
  p_start_at timestamptz default null,
  p_end_at timestamptz default null
)
returns table(
  id uuid,
  created_at timestamptz,
  action text,
  type text,
  visitor_name text,
  unit_label text,
  method text,
  plate text,
  has_evidence boolean
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_limit integer := least(greatest(coalesce(p_limit,20),1),51);
  v_offset integer := greatest(coalesce(p_offset,0),0);
  v_search text := nullif(lower(btrim(coalesce(p_search,''))),'');
  v_type text := nullif(upper(btrim(coalesce(p_type,''))),'');
  v_method text := nullif(upper(btrim(coalesce(p_method,''))),'');
  v_evidence text := nullif(upper(btrim(coalesce(p_evidence,''))),'');
begin
  if p_community_id is null then
    raise exception 'p_community_id is required' using errcode='22023';
  end if;

  if not exists (
    select 1 from public.community_members cm
    where cm.user_id=auth.uid()
      and cm.community_id=p_community_id
      and cm.is_active=true
      and cm.role::text in ('ADMIN','GUARD')
  ) then
    raise exception 'ADMIN or GUARD role required' using errcode='42501';
  end if;

  return query
  with base as (
    select
      el.id,
      el.action_at as created_at,
      el.action::text as action,
      coalesce(
        vp.pass_type::text,
        case
          when el.frequent_visitor_id is not null then 'FREQUENT'
          when el.visit_group_id is not null and vg.group_type::text='EVENT' then 'EVENT'
          when el.visit_group_member_id is not null or el.visit_group_id is not null then 'GROUP'
          when el.manual_entry_id is not null then 'MANUAL'
          else 'UNKNOWN'
        end
      ) as type,
      coalesce(vp.visitor_name,afv.full_name,vgm.visitor_name,me.manual_entry_name,'Sin nombre') as visitor_name,
      coalesce(h.house_label,me.destination_label,'Sin unidad') as unit_label,
      el.method::text as method,
      coalesce(el.vehicle_plate_text,vp.vehicle_plate) as plate,
      (el.photo_path is not null or el.vehicle_photo_path is not null) as has_evidence
    from public.entry_logs el
    left join public.houses h on h.id=el.house_id
    left join public.visit_passes vp on vp.id=el.pass_id
    left join public.authorized_frequent_visitors afv on afv.id=el.frequent_visitor_id
    left join public.visit_group_members vgm on vgm.id=el.visit_group_member_id
    left join public.visit_groups vg on vg.id=el.visit_group_id
    left join public.manual_entries me on me.id=el.manual_entry_id
    where el.community_id=p_community_id
      and (p_start_at is null or el.action_at>=p_start_at)
      and (p_end_at is null or el.action_at<=p_end_at)
  )
  select b.*
  from base b
  where (v_type is null or v_type='ALL' or upper(b.type)=v_type)
    and (v_method is null or v_method='ALL' or upper(b.method)=v_method)
    and (
      v_evidence is null or v_evidence='ALL'
      or (v_evidence='WITH_EVIDENCE' and b.has_evidence)
      or (v_evidence='WITHOUT_EVIDENCE' and not b.has_evidence)
    )
    and (
      v_search is null
      or lower(coalesce(b.visitor_name,'') || ' ' || coalesce(b.unit_label,'') || ' ' ||
               coalesce(b.plate,'') || ' ' || coalesce(b.method,'') || ' ' || coalesce(b.type,'')) like '%' || v_search || '%'
    )
  order by b.created_at desc
  limit v_limit
  offset v_offset;
end;
$$;

revoke all on function public.admin_list_access_history_v2(uuid,integer,integer,text,text,text,text,timestamptz,timestamptz)
  from public, anon;
grant execute on function public.admin_list_access_history_v2(uuid,integer,integer,text,text,text,text,timestamptz,timestamptz)
  to authenticated, service_role;

create or replace function public.reconcile_entry_observability_incidents_v1()
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_opened integer := 0;
  v_resolved integer := 0;
begin
  if coalesce(current_setting('request.jwt.claim.role',true),'') <> 'service_role'
     and not public.is_superadmin() then
    raise exception 'Service or superadmin access required' using errcode='42501';
  end if;

  create temporary table if not exists pg_temp.entry_obs_desired_incidents (
    fingerprint text not null,
    scope_key text not null,
    community_id uuid null,
    capability text not null,
    event_type text not null,
    error_code text null,
    severity text not null,
    details jsonb not null
  ) on commit drop;
  truncate pg_temp.entry_obs_desired_incidents;

  insert into pg_temp.entry_obs_desired_incidents
  with resident_population as (
    select p.user_id,p.community_id,p.house_id
    from public.profiles p
    join public.community_members cm
      on cm.user_id=p.user_id and cm.community_id=p.community_id and cm.is_active=true
    join public.communities c on c.id=p.community_id and coalesce(c.is_active,false)=true
    where p.role::text='RESIDENT' and p.is_active=true
  ),
  resident_check as (
    select rp.*,
      (
        rp.house_id is not null
        and (
          select count(*)
          from public.house_residents hr
          join public.houses h on h.id=hr.house_id and h.community_id=hr.community_id
          where hr.user_id=rp.user_id
            and hr.community_id=rp.community_id
            and hr.house_id=rp.house_id
            and hr.is_active=true
            and hr.is_primary=true
            and h.is_active=true
        ) = 1
      ) as valid
    from resident_population rp
  )
  select
    'resident_access:resident_house_context_invalid',
    rc.community_id::text,
    rc.community_id,
    'resident_access',
    'RESIDENT_HOUSE_CONTEXT_INVALID',
    'RESIDENT_HOUSE_CONTEXT_INVALID',
    case when count(*) filter(where not rc.valid)=count(*) then 'CRITICAL' else 'ERROR' end,
    jsonb_build_object(
      'active_residents',count(*),
      'invalid_residents',count(*) filter(where not rc.valid)
    )
  from resident_check rc
  group by rc.community_id
  having count(*) filter(where not rc.valid)>0;

  insert into pg_temp.entry_obs_desired_incidents
  select
    'communications:notification_worker_unhealthy',
    'global',
    null,
    'communications',
    'COMMUNICATIONS_WORKER_UNHEALTHY',
    coalesce(h.last_error_code,'COMMUNICATIONS_WORKER_STALE'),
    'ERROR',
    jsonb_strip_nulls(jsonb_build_object(
      'last_cycle_at',h.last_cycle_at,
      'last_status',h.last_status,
      'last_failure_at',h.last_failure_at
    ))
  from public.entry_notification_worker_health h
  where h.worker_name='community_message_push'
    and (
      h.last_cycle_at is null
      or h.last_cycle_at < now()-interval '6 minutes'
      or h.last_status='failure'
    );

  insert into pg_temp.entry_obs_desired_incidents
  select
    'communications:no_guard_push_coverage',
    cm.community_id::text,
    cm.community_id,
    'communications',
    'COMMUNICATIONS_GUARD_PUSH_UNAVAILABLE',
    'NO_GUARD_PUSH_COVERAGE',
    'WARNING',
    jsonb_build_object(
      'active_guards',count(distinct cm.user_id),
      'push_ready_guards',count(distinct upt.user_id)
    )
  from public.community_members cm
  join public.communities c on c.id=cm.community_id and coalesce(c.is_active,false)=true
  left join public.user_push_tokens upt
    on upt.user_id=cm.user_id and upt.community_id=cm.community_id and upt.is_active=true
  where cm.is_active=true and cm.role::text='GUARD'
  group by cm.community_id
  having count(distinct cm.user_id)>0 and count(distinct upt.user_id)=0;

  insert into pg_temp.entry_obs_desired_incidents
  select
    'communications:push_queue_stuck',
    q.community_id::text,
    q.community_id,
    'communications',
    'COMMUNICATIONS_QUEUE_STUCK',
    'PUSH_QUEUE_STUCK',
    'ERROR',
    jsonb_build_object(
      'stuck_count',count(*),
      'oldest_created_at',min(q.created_at)
    )
  from public.community_message_push_queue q
  where q.status in ('pending','processing')
    and q.created_at < now()-interval '10 minutes'
  group by q.community_id;

  insert into pg_temp.entry_obs_desired_incidents
  select
    'vision_recognition:ocr_queue_stuck',
    el.community_id::text,
    el.community_id,
    'vision_recognition',
    'OCR_QUEUE_STUCK',
    'OCR_QUEUE_STUCK',
    'ERROR',
    jsonb_build_object(
      'stuck_count',count(*),
      'oldest_created_at',min(q.created_at)
    )
  from public.plate_ocr_queue q
  join public.entry_logs el on el.id=q.entry_log_id
  where q.status in ('PENDING','PROCESSING')
    and q.created_at < now()-interval '15 minutes'
    and coalesce(q.scheduled_at,now()) <= now()
  group by el.community_id;

  insert into pg_temp.entry_obs_desired_incidents
  select
    'infrastructure:cron:' || j.jobname,
    'global',
    null,
    'infrastructure',
    'CRON_JOB_FAILED',
    'CRON_JOB_FAILED',
    'ERROR',
    jsonb_build_object(
      'job_name',j.jobname,
      'last_status',d.status,
      'last_started_at',d.start_time,
      'last_finished_at',d.end_time
    )
  from cron.job j
  join lateral (
    select d.*
    from cron.job_run_details d
    where d.jobid=j.jobid
    order by d.start_time desc
    limit 1
  ) d on true
  where j.active=true and d.status<>'succeeded';

  insert into public.entry_observability_incidents (
    fingerprint,scope_key,community_id,capability,event_type,error_code,severity,status,
    first_seen_at,last_seen_at,resolved_at,occurrence_count,last_details,updated_at
  )
  select
    d.fingerprint,d.scope_key,d.community_id,d.capability,d.event_type,d.error_code,d.severity,'open',
    now(),now(),null,1,d.details,now()
  from pg_temp.entry_obs_desired_incidents d
  on conflict (fingerprint,scope_key) where status='open'
  do update set
    community_id=excluded.community_id,
    capability=excluded.capability,
    event_type=excluded.event_type,
    error_code=excluded.error_code,
    severity=excluded.severity,
    last_seen_at=now(),
    occurrence_count=public.entry_observability_incidents.occurrence_count+1,
    last_details=excluded.last_details,
    updated_at=now();

  get diagnostics v_opened = row_count;

  update public.entry_observability_incidents i
  set status='resolved',
      resolved_at=now(),
      updated_at=now()
  where i.status='open'
    and i.fingerprint in (
      'resident_access:resident_house_context_invalid',
      'communications:notification_worker_unhealthy',
      'communications:no_guard_push_coverage',
      'communications:push_queue_stuck',
      'vision_recognition:ocr_queue_stuck'
    )
    and not exists (
      select 1
      from pg_temp.entry_obs_desired_incidents d
      where d.fingerprint=i.fingerprint and d.scope_key=i.scope_key
    );

  get diagnostics v_resolved = row_count;

  update public.entry_observability_incidents i
  set status='resolved',resolved_at=now(),updated_at=now()
  where i.status='open'
    and i.fingerprint like 'infrastructure:cron:%'
    and not exists (
      select 1 from pg_temp.entry_obs_desired_incidents d
      where d.fingerprint=i.fingerprint and d.scope_key=i.scope_key
    );

  return jsonb_build_object(
    'desired', (select count(*) from pg_temp.entry_obs_desired_incidents),
    'upserted', v_opened,
    'resolved', v_resolved,
    'checked_at', now()
  );
end;
$$;

revoke all on function public.reconcile_entry_observability_incidents_v1() from public, anon, authenticated;
grant execute on function public.reconcile_entry_observability_incidents_v1() to service_role;

create or replace function public.maintain_entry_observability_retention_v1()
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_perf integer;
  v_heartbeat integer;
  v_incidents integer;
begin
  if coalesce(current_setting('request.jwt.claim.role',true),'') <> 'service_role' then
    raise exception 'Service role required' using errcode='42501';
  end if;

  delete from public.entry_performance_events
  where created_at < now()-interval '45 days';
  get diagnostics v_perf = row_count;

  delete from public.system_event_log
  where event_type='ENTRY_WEB_PUSH_DISPATCH_COMPLETED'
    and severity='INFO'
    and created_at < now()-interval '7 days';
  get diagnostics v_heartbeat = row_count;

  delete from public.entry_observability_incidents
  where status='resolved'
    and resolved_at < now()-interval '180 days';
  get diagnostics v_incidents = row_count;

  return jsonb_build_object(
    'performance_deleted',v_perf,
    'heartbeat_deleted',v_heartbeat,
    'incidents_deleted',v_incidents,
    'maintained_at',now()
  );
end;
$$;

revoke all on function public.maintain_entry_observability_retention_v1() from public, anon, authenticated;
grant execute on function public.maintain_entry_observability_retention_v1() to service_role;

create or replace function public.sa_get_entry_observability_v3(
  p_starts_at timestamptz,
  p_ends_at timestamptz default now(),
  p_community_id uuid default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_start timestamptz := coalesce(p_starts_at,now()-interval '24 hours');
  v_end timestamptz := coalesce(p_ends_at,now());
  v_result jsonb;
  v_admin_flow jsonb;
  v_flows jsonb;
  v_incidents jsonb;
  v_perf jsonb;
  v_infra jsonb;
  v_readiness jsonb;
  v_history jsonb;
  v_status text;
begin
  if not public.is_superadmin() then
    raise exception 'Superadmin access required' using errcode='42501';
  end if;
  if v_end<=v_start or v_end-v_start>interval '31 days' then
    raise exception 'Invalid observability time range' using errcode='22023';
  end if;

  v_result := public.sa_get_entry_observability_v2(v_start,v_end,p_community_id);

  with a as (
    select
      count(*)::integer as evidence_count,
      count(*) filter(where s.event_type='ADMIN_OPERATION_SUCCEEDED')::integer as success_count,
      count(*) filter(where s.event_type='ADMIN_OPERATION_FAILED')::integer as failure_count,
      max(s.created_at) filter(where s.event_type='ADMIN_OPERATION_SUCCEEDED') as last_success_at,
      max(s.created_at) as last_seen_at,
      percentile_cont(0.95) within group (
        order by public._entry_observability_jsonb_integer_v1(s.details,'duration_ms')
      ) filter(where public._entry_observability_jsonb_integer_v1(s.details,'duration_ms') is not null) as p95
    from public.system_event_log s
    where s.created_at>=v_start and s.created_at<v_end
      and s.event_type in ('ADMIN_OPERATION_SUCCEEDED','ADMIN_OPERATION_FAILED')
      and (
        p_community_id is null
        or s.community_id=p_community_id
      )
  )
  select jsonb_build_object(
    'key','administration',
    'label','Administration',
    'status',case when evidence_count=0 then 'idle'
      else public._entry_observability_flow_status_v1(success_count,failure_count,last_success_at,evidence_count) end,
    'success_count',success_count,
    'failure_count',failure_count,
    'evidence_count',evidence_count,
    'last_success_at',last_success_at,
    'last_seen_at',last_seen_at,
    'p95_latency_ms',round(p95::numeric,0),
    'health_mode','workload'
  ) into v_admin_flow from a;

  v_flows := coalesce(v_result->'critical_flows','[]'::jsonb) || jsonb_build_array(v_admin_flow);

  select coalesce(jsonb_agg(x.payload order by x.ordinal),'[]'::jsonb)
  into v_incidents
  from (
    select e.value as payload,e.ordinality::integer as ordinal
    from jsonb_array_elements(coalesce(v_result->'incidents','[]'::jsonb)) with ordinality e(value,ordinality)
    union all
    select
      jsonb_build_object(
        'fingerprint',i.fingerprint,
        'severity',i.severity,
        'source','incident_monitor',
        'event_type',i.event_type,
        'error_code',i.error_code,
        'occurrence_count',i.occurrence_count,
        'affected_community_count',case when i.community_id is null then 0 else 1 end,
        'first_seen_at',i.first_seen_at,
        'last_seen_at',i.last_seen_at,
        'explanation',case
          when i.event_type='COMMUNICATIONS_GUARD_PUSH_UNAVAILABLE'
            then 'Active guards exist, but none currently have a registered mobile push token.'
          when i.event_type='COMMUNICATIONS_QUEUE_STUCK'
            then 'Communication work has remained pending or processing beyond the expected queue window.'
          when i.event_type='OCR_QUEUE_STUCK'
            then 'Vision work has remained pending or processing beyond the expected queue window.'
          when i.event_type='CRON_JOB_FAILED'
            then 'A scheduled ENTRY background job latest run failed.'
          else 'A current ENTRY monitor detected an operational condition that needs review.'
        end,
        'communities',case when i.community_id is null then '[]'::jsonb else jsonb_build_array(
          jsonb_build_object(
            'community_id',i.community_id,
            'community_name',coalesce(c.name,'Unknown community'),
            'occurrence_count',i.occurrence_count
          )
        ) end
      ),
      1000 + row_number() over(order by i.severity desc,i.last_seen_at desc)
    from public.entry_observability_incidents i
    left join public.communities c on c.id=i.community_id
    where i.status='open'
      and (p_community_id is null or i.community_id=p_community_id or i.community_id is null)
      and not exists (
        select 1
        from jsonb_array_elements(coalesce(v_result->'incidents','[]'::jsonb)) b
        where b->>'fingerprint'=i.fingerprint
      )
  ) x;

  with perf as (
    select *
    from public.entry_performance_events p
    where p.created_at>=v_start and p.created_at<v_end
      and (p_community_id is null or p.community_id=p_community_id)
  ),
  total as (
    select
      count(*)::integer as event_count,
      count(*) filter(where status='failed')::integer as failed_count,
      percentile_cont(0.50) within group(order by duration_ms) as p50,
      percentile_cont(0.95) within group(order by duration_ms) as p95,
      percentile_cont(0.99) within group(order by duration_ms) as p99,
      max(created_at) as last_seen_at
    from perf
  ),
  metric_rows as (
    select
      source_surface,metric_name,platform,app_version,
      count(*)::integer as event_count,
      count(*) filter(where status='failed')::integer as failed_count,
      percentile_cont(0.50) within group(order by duration_ms) as p50,
      percentile_cont(0.95) within group(order by duration_ms) as p95,
      percentile_cont(0.99) within group(order by duration_ms) as p99,
      max(created_at) as last_seen_at
    from perf
    group by source_surface,metric_name,platform,app_version
  )
  select jsonb_build_object(
    'summary',jsonb_build_object(
      'event_count',t.event_count,
      'failed_count',t.failed_count,
      'p50_ms',round(t.p50::numeric,0),
      'p95_ms',round(t.p95::numeric,0),
      'p99_ms',round(t.p99::numeric,0),
      'last_seen_at',t.last_seen_at
    ),
    'metrics',coalesce((
      select jsonb_agg(jsonb_build_object(
        'surface',m.source_surface,
        'metric',m.metric_name,
        'platform',m.platform,
        'app_version',m.app_version,
        'event_count',m.event_count,
        'failed_count',m.failed_count,
        'p50_ms',round(m.p50::numeric,0),
        'p95_ms',round(m.p95::numeric,0),
        'p99_ms',round(m.p99::numeric,0),
        'last_seen_at',m.last_seen_at
      ) order by m.event_count desc,m.source_surface,m.metric_name)
      from (select * from metric_rows order by event_count desc limit 24) m
    ),'[]'::jsonb)
  )
  into v_perf
  from total t;

  with latest_runs as (
    select
      j.jobid,j.jobname,j.schedule,j.active,
      d.status,d.start_time,d.end_time,d.return_message,
      row_number() over(partition by j.jobid order by d.start_time desc) as rn
    from cron.job j
    left join cron.job_run_details d on d.jobid=j.jobid
    where j.active=true
  ),
  queues as (
    select 'communications'::text as capability,'Mobile push queue'::text as name,
      count(*) filter(where q.status in ('pending','processing'))::integer as open_count,
      count(*) filter(where q.status='failed')::integer as failed_count,
      min(q.created_at) filter(where q.status in ('pending','processing')) as oldest_open_at
    from public.community_message_push_queue q
    where p_community_id is null or q.community_id=p_community_id
    union all
    select 'vision_recognition','OCR queue',
      count(*) filter(where q.status in ('PENDING','PROCESSING'))::integer,
      count(*) filter(where q.status='FAILED')::integer,
      min(q.created_at) filter(where q.status in ('PENDING','PROCESSING'))
    from public.plate_ocr_queue q
    join public.entry_logs el on el.id=q.entry_log_id
    where p_community_id is null or el.community_id=p_community_id
    union all
    select 'onboarding','Activation queue',
      count(*) filter(where q.status in ('pending','invited'))::integer,
      0,
      min(q.created_at) filter(where q.status in ('pending','invited'))
    from public.resident_activation_queue q
    where p_community_id is null or q.community_id=p_community_id
  ),
  db as (
    select
      numbackends as connections,
      deadlocks,
      conflicts,
      stats_reset,
      case when blks_hit+blks_read=0 then null
        else round((blks_hit::numeric/(blks_hit+blks_read))*100,2) end as cache_hit_percent
    from pg_stat_database where datname=current_database()
  )
  select jsonb_build_object(
    'workers',coalesce((
      select jsonb_agg(jsonb_build_object(
        'name',r.jobname,
        'schedule',r.schedule,
        'status',coalesce(r.status,'unknown'),
        'last_started_at',r.start_time,
        'last_finished_at',r.end_time
      ) order by r.jobname)
      from latest_runs r where r.rn=1
    ),'[]'::jsonb),
    'queues',coalesce((
      select jsonb_agg(jsonb_build_object(
        'capability',q.capability,
        'name',q.name,
        'open_count',q.open_count,
        'failed_count',q.failed_count,
        'oldest_open_at',q.oldest_open_at
      ) order by q.name)
      from queues q
    ),'[]'::jsonb),
    'database',(select jsonb_build_object(
      'connections',d.connections,
      'deadlocks',d.deadlocks,
      'conflicts',d.conflicts,
      'cache_hit_percent',d.cache_hit_percent,
      'stats_reset',d.stats_reset
    ) from db d)
  ) into v_infra;

  with selected as (
    select c.id,c.name
    from public.communities c
    where coalesce(c.is_active,false)=true
      and (p_community_id is null or c.id=p_community_id)
  ),
  members as (
    select
      s.id as community_id,s.name,
      count(distinct cm.user_id) filter(where cm.role::text='RESIDENT' and cm.is_active=true) as active_residents,
      count(distinct upt.user_id) filter(where cm.role::text='RESIDENT' and cm.is_active=true and upt.user_id is not null) as push_residents,
      count(distinct cm.user_id) filter(where cm.role::text='GUARD' and cm.is_active=true) as active_guards,
      count(distinct upt.user_id) filter(where cm.role::text='GUARD' and cm.is_active=true and upt.user_id is not null) as push_guards
    from selected s
    left join public.community_members cm on cm.community_id=s.id
    left join public.user_push_tokens upt
      on upt.user_id=cm.user_id and upt.community_id=cm.community_id and upt.is_active=true
    group by s.id,s.name
  ),
  rollout as (
    select
      s.id as community_id,
      (select count(*) from public.resident_activation_queue q where q.community_id=s.id and q.status='activated') as activated_residents,
      (select count(*) from public.visit_passes vp where vp.community_id=s.id) as passes_created,
      (select count(*) from public.entry_logs el where el.community_id=s.id) as gate_accesses,
      (select count(*) from public.community_messages m where m.community_id=s.id and m.deleted_at is null) as messages_published
    from selected s
  )
  select jsonb_build_object(
    'communities',coalesce(jsonb_agg(jsonb_build_object(
      'community_id',m.community_id,
      'community_name',m.name,
      'active_residents',m.active_residents,
      'push_ready_residents',m.push_residents,
      'active_guards',m.active_guards,
      'push_ready_guards',m.push_guards,
      'activated_residents',r.activated_residents,
      'passes_created',r.passes_created,
      'gate_accesses',r.gate_accesses,
      'messages_published',r.messages_published
    ) order by m.name),'[]'::jsonb)
  )
  into v_readiness
  from members m
  join rollout r on r.community_id=m.community_id;

  select coalesce(jsonb_agg(jsonb_build_object(
    'id',i.id,
    'fingerprint',i.fingerprint,
    'capability',i.capability,
    'event_type',i.event_type,
    'error_code',i.error_code,
    'severity',i.severity,
    'status',i.status,
    'community_id',i.community_id,
    'community_name',c.name,
    'first_seen_at',i.first_seen_at,
    'last_seen_at',i.last_seen_at,
    'resolved_at',i.resolved_at,
    'occurrence_count',i.occurrence_count,
    'details',i.last_details
  ) order by coalesce(i.resolved_at,i.last_seen_at) desc),'[]'::jsonb)
  into v_history
  from public.entry_observability_incidents i
  left join public.communities c on c.id=i.community_id
  where (p_community_id is null or i.community_id=p_community_id or i.community_id is null)
    and (
      i.status='open'
      or coalesce(i.resolved_at,i.last_seen_at)>=v_start
    );

  v_result := jsonb_set(v_result,'{critical_flows}',v_flows,true);
  v_result := jsonb_set(v_result,'{incidents}',coalesce(v_incidents,'[]'::jsonb),true);
  v_result := jsonb_set(v_result,'{performance}',coalesce(v_perf,'{}'::jsonb),true);
  v_result := jsonb_set(v_result,'{infrastructure}',coalesce(v_infra,'{}'::jsonb),true);
  v_result := jsonb_set(v_result,'{readiness}',coalesce(v_readiness,'{}'::jsonb),true);
  v_result := jsonb_set(v_result,'{incident_history}',coalesce(v_history,'[]'::jsonb),true);

  select case
    when exists(select 1 from jsonb_array_elements(v_flows) f where f->>'status'='down') then 'down'
    when exists(select 1 from jsonb_array_elements(coalesce(v_incidents,'[]'::jsonb)) i where i->>'severity' in ('CRITICAL','ERROR')) then 'degraded'
    when exists(select 1 from jsonb_array_elements(v_flows) f where f->>'status'='degraded') then 'degraded'
    when exists(select 1 from jsonb_array_elements(v_flows) f where f->>'status'='unknown') then 'unknown'
    else 'healthy'
  end into v_status;

  v_result := jsonb_set(v_result,'{summary,system_status}',to_jsonb(v_status),true);
  return v_result;
end;
$$;

revoke all on function public.sa_get_entry_observability_v3(timestamptz,timestamptz,uuid) from public, anon;
grant execute on function public.sa_get_entry_observability_v3(timestamptz,timestamptz,uuid)
  to authenticated, service_role;

comment on function public.sa_get_entry_observability_v3(timestamptz,timestamptz,uuid) is
  'ENTRY superadmin observability read model with durable incidents, Administration capability, performance, infrastructure, readiness, and incident history.';

do $$
declare
  v_jobid bigint;
begin
  select jobid into v_jobid from cron.job where jobname='entry-observability-incident-reconcile';
  if v_jobid is not null then perform cron.unschedule(v_jobid); end if;
  perform cron.schedule(
    'entry-observability-incident-reconcile',
    '*/5 * * * *',
    'select public.reconcile_entry_observability_incidents_v1();'
  );

  select jobid into v_jobid from cron.job where jobname='entry-observability-retention';
  if v_jobid is not null then perform cron.unschedule(v_jobid); end if;
  perform cron.schedule(
    'entry-observability-retention',
    '20 4 * * *',
    'select public.maintain_entry_observability_retention_v1();'
  );
end $$;
